-- mostly players with missing data or data collection error or link error with a few examples (mike williams - DET - was not eligible for draft in 2004
-- if i have time i can go through 1-by-1
select p.player,p.ncaa_link
from [dbo].[player_stats_raw_avg_pg_prior] p
left join [dbo].[player_stats_raw_avg_pg_draft_year] d
on d.ncaa_link=p.ncaa_link
where d.ncaa_link is null

-- mostly missing data or only 1 college year played
select d.player,d.ncaa_link
from [dbo].[player_stats_raw_avg_pg_draft_year] d
left join [dbo].[player_stats_raw_avg_pg_prior] p
on d.ncaa_link=p.ncaa_link
where p.ncaa_link is null

select d.player,d.ncaa_link
from [dbo].[player_stats_raw_avg_pg_draft_year] d
inner join [dbo].[player_stats_raw_avg_pg_prior] p
on d.ncaa_link=p.ncaa_link

select ncaa_link, max(year) max_year from ncaa_player_stats_clean
where ncaa_link = 'http://www.sports-reference.com/cfb/players/mike-williams-3.html'
and year<>'career' and year is not null
group by ncaa_link


ALTER TABLE ncaa_player_stats_clean
ADD max_year nvarchar(8)
GO

WITH CTE AS
(
    SELECT ncaa_link, max(year) max_year 
	FROM ncaa_player_stats_clean
	WHERE year<>'career' and year is not null
	--AND ncaa_link = 'http://www.sports-reference.com/cfb/players/mike-williams-3.html'
	GROUP BY ncaa_link
)
    UPDATE p
    SET p.max_year = cte.max_year
    FROM ncaa_player_stats_clean p
    INNER JOIN cte
    ON p.NCAA_Link = cte.NCAA_Link


SELECT p.NCAA_Link,p.max_year,c.Year, c.year-p.max_year dif
FROM [DataRobot].[dbo].[ncaa_player_stats_clean] p
INNER JOIN nfl_combine c ON c.NCAA_Link=p.NCAA_Link
where p.ncaa_link IN
('http://www.sports-reference.com/cfb/players/curtis-keaton-1.html',
'http://www.sports-reference.com/cfb/players/john-engelberger-1.html',
'http://www.sports-reference.com/cfb/players/rob-morris-1.html',
'http://www.sports-reference.com/cfb/players/ronney-jenkins-1.html',
'http://www.sports-reference.com/cfb/players/troy-hambrick-1.html',
'http://www.sports-reference.com/cfb/players/andre-lott-1.html',
'http://www.sports-reference.com/cfb/players/bryan-thomas-1.html',
'http://www.sports-reference.com/cfb/players/justin-bannan-1.html',
'http://www.sports-reference.com/cfb/players/mike-rumph-1.html',
'http://www.sports-reference.com/cfb/players/ron-israel-1.html',
'http://www.sports-reference.com/cfb/players/boss-bailey-1.html',
'http://www.sports-reference.com/cfb/players/cato-june-1.html',
'http://www.sports-reference.com/cfb/players/cory-redding-1.html',
'http://www.sports-reference.com/cfb/players/jerome-mcdougle-1.html',
'http://www.sports-reference.com/cfb/players/jordan-black-1.html',
'http://www.sports-reference.com/cfb/players/wayne-lucier-1.html',
'http://www.sports-reference.com/cfb/players/tim-anderson-1.html',
'http://www.sports-reference.com/cfb/players/trevor-johnson-1.html',
'http://www.sports-reference.com/cfb/players/adam-seward-1.html',
'http://www.sports-reference.com/cfb/players/brady-poppinga-1.html',
'http://www.sports-reference.com/cfb/players/derrick-johnson-4.html',
'http://www.sports-reference.com/cfb/players/mike-williams-3.html',
'http://www.sports-reference.com/cfb/players/arron-sears-1.html',
'http://www.sports-reference.com/cfb/players/levi-brown-2.html',
'http://www.sports-reference.com/cfb/players/manuel-ramirez-1.html',
'http://www.sports-reference.com/cfb/players/syvelle-newton-1.html',
'http://www.sports-reference.com/cfb/players/tony-ugoh-1.html',
'http://www.sports-reference.com/cfb/players/chad-simpson-1.html',
'http://www.sports-reference.com/cfb/players/jeff-otah-1.html',
'http://www.sports-reference.com/cfb/players/jason-smith-3.html',
'http://www.sports-reference.com/cfb/players/kraig-urbik-1.html',
'http://www.sports-reference.com/cfb/players/charles-brown-6.html',
'http://www.sports-reference.com/cfb/players/joe-hawley-1.html',
'http://www.sports-reference.com/cfb/players/preston-parker-1.html',
'http://www.sports-reference.com/cfb/players/danny-watkins-1.html',
'http://www.sports-reference.com/cfb/players/jarriel-king-1.html',
'http://www.sports-reference.com/cfb/players/joseph-barksdale-1.html',
'http://www.sports-reference.com/cfb/players/robert-quinn-1.html',
'http://www.sports-reference.com/cfb/players/weslye-saunders-1.html',
'http://www.sports-reference.com/cfb/players/janoris-jenkins-1.html',
'http://www.sports-reference.com/cfb/players/matt-reynolds-1.html',
'http://www.sports-reference.com/cfb/players/dj-fluker-1.html',
'http://www.sports-reference.com/cfb/players/jordan-mills-1.html',
'http://www.sports-reference.com/cfb/players/luke-joeckel-1.html',
'http://www.sports-reference.com/cfb/players/travis-bond-1.html',
'http://www.sports-reference.com/cfb/players/tyrann-mathieu-1.html',
'http://www.sports-reference.com/cfb/players/anthony-steen-1.html',
'http://www.sports-reference.com/cfb/players/brandon-thomas-3.html',
'http://www.sports-reference.com/cfb/players/chris-boyd-1.html',
'http://www.sports-reference.com/cfb/players/gabe-ikard-1.html',
'http://www.sports-reference.com/cfb/players/ha-ha-clinton-dix-1.html',
'http://www.sports-reference.com/cfb/players/russell-bodine-1.html',
'http://www.sports-reference.com/cfb/players/ryan-groy-1.html',
'http://www.sports-reference.com/cfb/players/zack-martin-1.html',
'http://www.sports-reference.com/cfb/players/dorial-green-beckham-1.html',
'http://www.sports-reference.com/cfb/players/greg-mancz-1.html',
'http://www.sports-reference.com/cfb/players/lael-collins-1.html',
'http://www.sports-reference.com/cfb/players/reese-dismukes-1.html',
'http://www.sports-reference.com/cfb/players/cam-robinson-2.html',
'http://www.sports-reference.com/cfb/players/kyle-fuller-2.html',
'http://www.sports-reference.com/cfb/players/pat-elfein-1.html',
'http://www.sports-reference.com/cfb/players/sean-harlow-1.html',
'http://www.sports-reference.com/cfb/players/chukwuma-okorafor-1.html',
'http://www.sports-reference.com/cfb/players/cole-madison-1.html',
'http://www.sports-reference.com/cfb/players/kahlil-mckenzie-1.html',
'http://www.sports-reference.com/cfb/players/martinas-rankin-1.html',
'http://www.sports-reference.com/cfb/players/hjalte-froholdt-1.html',
'http://www.sports-reference.com/cfb/players/nate-davis-4.html',
'http://www.sports-reference.com/cfb/players/ryan-bates-1.html',
'http://www.sports-reference.com/cfb/players/yosuah-nijman-1.html',
'http://www.sports-reference.com/cfb/players/cesar-ruiz-1.html',
'http://www.sports-reference.com/cfb/players/jonah-jackson-1.html',
'http://www.sports-reference.com/cfb/players/robert-hunt-1.html',
'http://www.sports-reference.com/cfb/players/mario-edwards-3.html',
'http://www.sports-reference.com/cfb/players/spergon-wynn-1.html',
'http://www.sports-reference.com/cfb/players/antoine-harris-1.html',
'http://www.sports-reference.com/cfb/players/matt-light-1.html',
'http://www.sports-reference.com/cfb/players/monty-beisel-1.html',
'http://www.sports-reference.com/cfb/players/kalimba-edwards-1.html',
'http://www.sports-reference.com/cfb/players/terreal-bierria-1.html',
'http://www.sports-reference.com/cfb/players/will-overstreet-1.html',
'http://www.sports-reference.com/cfb/players/angelo-crowell-1.html',
'http://www.sports-reference.com/cfb/players/eddie-moore-1.html',
'http://www.sports-reference.com/cfb/players/mario-haggan-1.html',
'http://www.sports-reference.com/cfb/players/steve-sciullo-1.html',
'http://www.sports-reference.com/cfb/players/tony-gilbert-1.html',
'http://www.sports-reference.com/cfb/players/spencer-johnson-1.html',
'http://www.sports-reference.com/cfb/players/barrett-ruud-1.html',
'http://www.sports-reference.com/cfb/players/dustin-fox-1.html',
'http://www.sports-reference.com/cfb/players/khalif-barnes-1.html',
'http://www.sports-reference.com/cfb/players/maurice-clarett-1.html',
'http://www.sports-reference.com/cfb/players/mike-patterson-1.html',
'http://www.sports-reference.com/cfb/players/odell-thurman-1.html',
'http://www.sports-reference.com/cfb/players/eric-winston-1.html',
'http://www.sports-reference.com/cfb/players/gary-russell-1.html',
'http://www.sports-reference.com/cfb/players/matt-gutierrez-1.html',
'http://www.sports-reference.com/cfb/players/samson-satele-1.html',
'http://www.sports-reference.com/cfb/players/joe-flacco-1.html',
'http://www.sports-reference.com/cfb/players/william-robinson-1.html',
'http://www.sports-reference.com/cfb/players/eben-britton-1.html',
'http://www.sports-reference.com/cfb/players/eugene-monroe-1.html',
'http://www.sports-reference.com/cfb/players/bruce-campbell-2.html',
'http://www.sports-reference.com/cfb/players/eric-olsen-1.html',
'http://www.sports-reference.com/cfb/players/jason-fox-1.html',
'http://www.sports-reference.com/cfb/players/jd-walton-1.html',
'http://www.sports-reference.com/cfb/players/rodger-saffold-1.html',
'http://www.sports-reference.com/cfb/players/selvish-capers-1.html',
'http://www.sports-reference.com/cfb/players/clint-boling-1.html',
'http://www.sports-reference.com/cfb/players/julian-vandervelde-1.html',
'http://www.sports-reference.com/cfb/players/andrew-datko-1.html',
'http://www.sports-reference.com/cfb/players/chaz-powell-1.html',
'http://www.sports-reference.com/cfb/players/dajohn-harris-2.html',
'http://www.sports-reference.com/cfb/players/jeff-allen-2.html',
'http://www.sports-reference.com/cfb/players/lucas-nix-1.html',
'http://www.sports-reference.com/cfb/players/zebrie-sanders-1.html',
'http://www.sports-reference.com/cfb/players/brennan-williams-1.html',
'http://www.sports-reference.com/cfb/players/greg-robinson-3.html',
'http://www.sports-reference.com/cfb/players/jawuan-james-1.html',
'http://www.sports-reference.com/cfb/players/justin-britt-2.html',
'http://www.sports-reference.com/cfb/players/cameron-erving-1.html',
'http://www.sports-reference.com/cfb/players/josh-shaw-3.html',
'http://www.sports-reference.com/cfb/players/mark-glowinski-1.html',
'http://www.sports-reference.com/cfb/players/rob-havenstein-1.html',
'http://www.sports-reference.com/cfb/players/tayo-fabuluje-1.html',
'http://www.sports-reference.com/cfb/players/ben-braden-1.html',
'http://www.sports-reference.com/cfb/players/taylor-moton-1.html',
'http://www.sports-reference.com/cfb/players/antonio-callaway-1.html',
'http://www.sports-reference.com/cfb/players/isaiah-wynn-1.html',
'http://www.sports-reference.com/cfb/players/jamarco-jones-1.html',
'http://www.sports-reference.com/cfb/players/joseph-noteboom-1.html',
'http://www.sports-reference.com/cfb/players/marcell-harris-1.html',
'http://www.sports-reference.com/cfb/players/salesi-uhatafe-1.html',
'http://www.sports-reference.com/cfb/players/scott-quessenberry-1.html',
'http://www.sports-reference.com/cfb/players/brandon-knight-2.html',
'http://www.sports-reference.com/cfb/players/dan-godsil-1.html',
'http://www.sports-reference.com/cfb/players/elgton-jenkins-1.html',
'http://www.sports-reference.com/cfb/players/jazz-ferguson-1.html',
'http://www.sports-reference.com/cfb/players/kaleb-mcgary-1.html',
'http://www.sports-reference.com/cfb/players/lamont-gaillard-1.html',
'http://www.sports-reference.com/cfb/players/martez-ivey-1.html',
'http://www.sports-reference.com/cfb/players/trevon-tate-1.html',
'http://www.sports-reference.com/cfb/players/tyler-jones-5.html',
'http://www.sports-reference.com/cfb/players/zack-bailey-1.html',
'http://www.sports-reference.com/cfb/players/michael-onwenu-1.html',
'http://www.sports-reference.com/cfb/players/reginald-robinson-ii-1.html',
'http://www.sports-reference.com/cfb/players/tristan-wirfs-1.html',
'http://www.sports-reference.com/cfb/players/john-jones-2.html',
'http://www.sports-reference.com/cfb/players/larry-foster-1.html',
'http://www.sports-reference.com/cfb/players/paul-zukauskas-1.html',
'http://www.sports-reference.com/cfb/players/ben-leber-1.html',
'http://www.sports-reference.com/cfb/players/chad-beasley-1.html',
'http://www.sports-reference.com/cfb/players/josh-mccown-1.html',
'http://www.sports-reference.com/cfb/players/kindal-moorehead-1.html',
'http://www.sports-reference.com/cfb/players/nick-barnett-1.html',
'http://www.sports-reference.com/cfb/players/wade-smith-1.html',
'http://www.sports-reference.com/cfb/players/andrae-thurman-1.html',
'http://www.sports-reference.com/cfb/players/jonathan-vilma-1.html',
'http://www.sports-reference.com/cfb/players/jon-bradley-1.html',
'http://www.sports-reference.com/cfb/players/karlos-dansby-1.html',
'http://www.sports-reference.com/cfb/players/keyaron-fox-1.html',
'http://www.sports-reference.com/cfb/players/matthias-askew-1.html',
'http://www.sports-reference.com/cfb/players/max-starks-1.html',
'http://www.sports-reference.com/cfb/players/stephen-peterman-1.html',
'http://www.sports-reference.com/cfb/players/vince-wilfork-1.html',
'http://www.sports-reference.com/cfb/players/chauncey-davis-1.html',
'http://www.sports-reference.com/cfb/players/corey-webster-1.html',
'http://www.sports-reference.com/cfb/players/derek-wake-1.html',
'http://www.sports-reference.com/cfb/players/antonio-cromartie-1.html',
'http://www.sports-reference.com/cfb/players/chris-chester-1.html',
'http://www.sports-reference.com/cfb/players/ingle-martin-1.html',
'http://www.sports-reference.com/cfb/players/rashad-butler-1.html',
'http://www.sports-reference.com/cfb/players/tarvaris-jackson-1.html',
'http://www.sports-reference.com/cfb/players/will-blackmon-1.html',
'http://www.sports-reference.com/cfb/players/dan-santucci-1.html',
'http://www.sports-reference.com/cfb/players/ryan-harris-1.html',
'http://www.sports-reference.com/cfb/players/breno-giacomini-1.html',
'http://www.sports-reference.com/cfb/players/barrett-green-1.html',
'http://www.sports-reference.com/cfb/players/justin-smith-8.html',
'http://www.sports-reference.com/cfb/players/charles-grant-1.html',
'http://www.sports-reference.com/cfb/players/jashon-sykes-1.html',
'http://www.sports-reference.com/cfb/players/aaron-hunt-2.html',
'http://www.sports-reference.com/cfb/players/antonio-garay-1.html',
'http://www.sports-reference.com/cfb/players/jeremi-johnson-1.html',
'http://www.sports-reference.com/cfb/players/roy-schuening-1.html',
'http://www.sports-reference.com/cfb/players/alex-mack-1.html',
'http://www.sports-reference.com/cfb/players/seth-olsen-1.html',
'http://www.sports-reference.com/cfb/players/brandon-carter-1.html',
'http://www.sports-reference.com/cfb/players/jermaine-gresham-1.html',
'http://www.sports-reference.com/cfb/players/jimmy-kennedy-1.html',
'http://www.sports-reference.com/cfb/players/matt-walters-1.html',
'http://www.sports-reference.com/cfb/players/omari-hand-1.html',
'http://www.sports-reference.com/cfb/players/tron-lafavor-1.html',
'http://www.sports-reference.com/cfb/players/william-joseph-1.html',
'http://www.sports-reference.com/cfb/players/craig-terrill-1.html',
'http://www.sports-reference.com/cfb/players/dexter-reid-1.html',
'http://www.sports-reference.com/cfb/players/igor-olshansky-1.html',
'http://www.sports-reference.com/cfb/players/khaleed-vaughn-1.html',
'http://www.sports-reference.com/cfb/players/michael-boulware-1.html',
'http://www.sports-reference.com/cfb/players/ryan-fowler-1.html',
'http://www.sports-reference.com/cfb/players/david-mcmillan-1.html',
'http://www.sports-reference.com/cfb/players/domonique-foxworth-1.html',
'http://www.sports-reference.com/cfb/players/jim-davis-1.html',
'http://www.sports-reference.com/cfb/players/jovan-haye-1.html',
'http://www.sports-reference.com/cfb/players/lorenzo-alexander-1.html',
'http://www.sports-reference.com/cfb/players/andrew-jackson-2.html',
'http://www.sports-reference.com/cfb/players/anthony-castonzo-1.html',
'http://www.sports-reference.com/cfb/players/mike-pouncey-1.html',
'http://www.sports-reference.com/cfb/players/ben-jones-3.html',
'http://www.sports-reference.com/cfb/players/cordy-glenn-1.html',
'http://www.sports-reference.com/cfb/players/mark-asper-1.html',
'http://www.sports-reference.com/cfb/players/omar-bolden-1.html',
'http://www.sports-reference.com/cfb/players/philip-blake-1.html',
'http://www.sports-reference.com/cfb/players/kamerion-wimbley-1.html',
'http://www.sports-reference.com/cfb/players/ben-patrick-1.html',
'http://www.sports-reference.com/cfb/players/chris-jones-7.html',
'http://www.sports-reference.com/cfb/players/larry-warford-1.html',
'http://www.sports-reference.com/cfb/players/jonotthan-harrison-1.html',
'http://www.sports-reference.com/cfb/players/travis-swanson-1.html',
'http://www.sports-reference.com/cfb/players/chaz-green-1.html',
'http://www.sports-reference.com/cfb/players/oniel-cousins-1.html',
'http://www.sports-reference.com/cfb/players/cj-davis-2.html',
'http://www.sports-reference.com/cfb/players/jamon-meredith-1.html',
'http://www.sports-reference.com/cfb/players/jonathan-luigs-1.html',
'http://www.sports-reference.com/cfb/players/anthony-davis-2.html',
'http://www.sports-reference.com/cfb/players/james-starks-1.html',
'http://www.sports-reference.com/cfb/players/junior-galette-1.html',
'http://www.sports-reference.com/cfb/players/jamon-brown-1.html',
'http://www.sports-reference.com/cfb/players/tj-clemmings-1.html',
'http://www.sports-reference.com/cfb/players/james-bradberry-1.html',
'http://www.sports-reference.com/cfb/players/noah-spence-1.html',
'http://www.sports-reference.com/cfb/players/adam-bisnowaty-1.html',
'http://www.sports-reference.com/cfb/players/al-quadin-muhammad-1.html',
'http://www.sports-reference.com/cfb/players/chase-roullier-1.html',
'http://www.sports-reference.com/cfb/players/damien-mama-1.html',
'http://www.sports-reference.com/cfb/players/kyle-williams-8.html',
'http://www.sports-reference.com/cfb/players/marshall-newhouse-1.html',
'http://www.sports-reference.com/cfb/players/rob-gronkowski-1.html',
'http://www.sports-reference.com/cfb/players/thomas-welch-1.html',
'http://www.sports-reference.com/cfb/players/greg-little-1.html',
'http://www.sports-reference.com/cfb/players/james-carpenter-1.html',
'http://www.sports-reference.com/cfb/players/keith-williams-8.html',
'http://www.sports-reference.com/cfb/players/marcus-cannon-1.html',
'http://www.sports-reference.com/cfb/players/marvin-austin-1.html',
'http://www.sports-reference.com/cfb/players/andrew-tiller-1.html',
'http://www.sports-reference.com/cfb/players/brandon-washington-3.html',
'http://www.sports-reference.com/cfb/players/donald-stephenson-1.html',
'http://www.sports-reference.com/cfb/players/jj-dielman-1.html',
'http://www.sports-reference.com/cfb/players/connor-williams-2.html',
'http://www.sports-reference.com/cfb/players/jack-cichy-1.html',
'http://www.sports-reference.com/cfb/players/derwin-gray-2.html',
'http://www.sports-reference.com/cfb/players/donnell-greene-1.html',
'http://www.sports-reference.com/cfb/players/dru-samia-1.html',
'http://www.sports-reference.com/cfb/players/ryan-miller-1.html',
'http://www.sports-reference.com/cfb/players/senio-kelemete-1.html',
'http://www.sports-reference.com/cfb/players/tony-bergstrom-1.html',
'http://www.sports-reference.com/cfb/players/john-jenkins-4.html',
'http://www.sports-reference.com/cfb/players/jonathan-cooper-1.html',
'http://www.sports-reference.com/cfb/players/lane-johnson-1.html',
'http://www.sports-reference.com/cfb/players/cameron-fleming-1.html',
'http://www.sports-reference.com/cfb/players/charles-leno-1.html',
'http://www.sports-reference.com/cfb/players/chris-watt-1.html',
'http://www.sports-reference.com/cfb/players/james-stone-1.html',
'http://www.sports-reference.com/cfb/players/michael-schofield-1.html',
'http://www.sports-reference.com/cfb/players/morgan-moses-1.html',
'http://www.sports-reference.com/cfb/players/blake-ferguson-3.html',
'http://www.sports-reference.com/cfb/players/colton-mckivitz-1.html',
'http://www.sports-reference.com/cfb/players/justin-herron-1.html',
'http://www.sports-reference.com/cfb/players/logan-stenberg-1.html',
'http://www.sports-reference.com/cfb/players/simon-stepaniak-1.html',
'http://www.sports-reference.com/cfb/players/terence-steele-1.html',
'http://www.sports-reference.com/cfb/players/trey-adams-2.html',
'http://www.sports-reference.com/cfb/players/tyre-phillips-1.html',
'http://www.sports-reference.com/cfb/players/corey-robinson-2.html',
'http://www.sports-reference.com/cfb/players/rashard-robinson-1.html',
'http://www.sports-reference.com/cfb/players/aviante-collins-1.html',
'http://www.sports-reference.com/cfb/players/sam-tevi-1.html',
'http://www.sports-reference.com/cfb/players/brian-allen-8.html',
'http://www.sports-reference.com/cfb/players/coleman-shelton-1.html',
'http://www.sports-reference.com/cfb/players/frank-ragnow-1.html',
'http://www.sports-reference.com/cfb/players/beau-benzschawel-1.html',
'http://www.sports-reference.com/cfb/players/dalton-risner-1.html',
'http://www.sports-reference.com/cfb/players/max-scharping-1.html',
'http://www.sports-reference.com/cfb/players/nate-herbig-1.html',
'http://www.sports-reference.com/cfb/players/ryan-pope-1.html',
'http://www.sports-reference.com/cfb/players/tremayne-anchrum-1.html',
'http://www.sports-reference.com/cfb/players/yasir-durant-1.html')
AND p.max_year=p.year
order by dif desc